//! Running a project built from `.rs` assets: `assets::project()` (generated by
//! `xerxes_build`) gives the settings, bundles, metas and logic modules; [`launch_project`]
//! runs them the same way on every platform:
//!
//! ```text
//! window (settings) → Preload (bundles) → Splash → MainMenu → Level # (see `flow`)
//! ```

use std::collections::HashMap;

use bevy::asset::AssetMetaCheck;
use bevy::asset::io::memory::Dir;
use bevy::prelude::*;
use bevy::window::WindowPlugin;

use crate::modules::assets::meta::AssetMeta;
use crate::modules::bundles::{
    self, BundleInfo, BundleReady, BundleZip, BundleZipLoader, Bundles, LoadBundle,
};
use crate::modules::flow::{FlowConfig, FlowPlugin};

pub mod settings;

use self::settings::update_actions;
pub use self::settings::{
    Actions, BackendSettings, Binding, GameBackend, InputMap, ProjectSettings, WindowSettings,
};

/// Everything `xerxes_build` generated for a game (`assets::project()`).
pub struct Project {
    pub settings: ProjectSettings,
    pub bundles: &'static [BundleInfo],
    pub metas: &'static [(&'static str, fn() -> AssetMeta)],
    /// Each logic module's `plugin` (its systems and resources).
    pub logic: &'static [fn(&mut App)],
}

/// Runs a project on this platform.
pub fn launch_project(project: Project) {
    project_app(project).run();
}

/// Where the shipped files (`public/`) are, per platform. Android reads the APK's assets
/// root and ignores it; the web build serves `public/` at the site root.
fn shipped_root() -> &'static str {
    if cfg!(target_arch = "wasm32") {
        ""
    } else {
        "public"
    }
}

/// The primary window. Window size is a desktop option: the web canvas fills its page and
/// Android is fullscreen, so a fixed resolution there would fight the platform.
fn window(settings: &ProjectSettings) -> Window {
    let mut window = Window {
        title: settings.title.into(),
        resizable: settings.window.resizable,
        fit_canvas_to_parent: true,
        ..default()
    };
    if !cfg!(any(target_arch = "wasm32", target_os = "android")) {
        window.resolution = (settings.window.width, settings.window.height).into();
    }
    window
}

/// The Bevy app for a project.
pub fn project_app(project: Project) -> App {
    let Project {
        settings,
        bundles,
        metas,
        logic,
    } = project;
    if let Err(err) = settings.flow.validate() {
        panic!("{}: {err}", settings.title);
    }
    let mut app = App::new();

    let dir = Dir::default();
    bundles::register_source(&mut app, &dir);
    app.add_plugins(
        DefaultPlugins
            .set(WindowPlugin {
                primary_window: Some(window(&settings)),
                ..default()
            })
            .set(AssetPlugin {
                file_path: shipped_root().into(),
                // Metas are compiled in; never ask the server for Bevy `.meta` files.
                meta_check: AssetMetaCheck::Never,
                ..default()
            }),
    );

    let metas: HashMap<_, _> = metas.iter().map(|(path, meta)| (*path, meta())).collect();
    app.init_asset::<BundleZip>()
        .register_asset_loader(BundleZipLoader)
        .add_message::<LoadBundle>()
        .add_message::<BundleReady>()
        .insert_resource(Bundles::new(dir, bundles, metas))
        .insert_resource(Actions::new(settings.input.clone()))
        .insert_resource(GameBackend(settings.backend.url()))
        .add_systems(PreUpdate, update_actions.after(bevy::input::InputSystems))
        .add_systems(
            Update,
            (bundles::start_loads, bundles::finish_loads).chain(),
        )
        .add_plugins(FlowPlugin(FlowConfig {
            settings: settings.flow.clone(),
            preload_bundles: settings.preload_bundles.clone(),
        }));

    bundles::texture::plugin(&mut app);
    for plugin in logic {
        plugin(&mut app);
    }
    app
}
